# Logistic Regression Classifier

In [2]:
import torch

# model parameters
w_1 = torch.tensor([0.23], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

# inputs and target
x_1 = torch.tensor([1.23])
y = torch.tensor([1.0])

u = x_1 * w_1
z = u + b
print(z)


a = torch.sigmoid(z)
print(a)

import torch.nn.functional as F

l = F.binary_cross_entropy(a, y)
print(l)



tensor([0.3829], grad_fn=<AddBackward0>)
tensor([0.5946], grad_fn=<SigmoidBackward0>)
tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)


NB:
---
In PyTorch it is best to us the binary_cross_entropy_with_logits than the binary_cross_entropy loss.

logits are net inputs of the logistic regression model. It is technical name for inputs to z

In [3]:
l = F.binary_cross_entropy_with_logits(a, y)
print(l)

# l.backward() Compute gradients automatically

tensor(0.4394, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


Automatic Differentiation using autograd

In [4]:
from torch.autograd import grad

grad_L_w1 = grad(l, b, retain_graph=True)
print(grad_L_w1)

(tensor([-0.0857]),)
